### PR TITLE
Implement a constructive method for Cookie

### PR DESCRIPTION
**Pull request by snylonue**
which is generic and probably has a better performance, though I did not perform any benchmark.

Also I did't perform any test because it is broken

### CODE REVIEW

**Comment by vkill** [comment]
> it is broken

Oh, because missing https://github.com/bk-rs/netscape-cookie/blob/83bdcb96780fc2beefe9f27f030ba726f7321d4b/src/lib.rs#L84 and https://github.com/bk-rs/netscape-cookie/blob/83bdcb96780fc2beefe9f27f030ba726f7321d4b/src/lib.rs#L88

**Comment by snylonue** [comment]
Yeah, I forgot dealing with the buffer and empty line. I'll fix it later.
But the test on master branch is broken as well.
```

running 2 tests
test feature_cookie::tests::test_convert ... ok
test tests::test_parse_demo ... FAILED

failures:

---- tests::test_parse_demo stdout ----
Error: "IncludeSubdomainsMissing"
thread 'tests::test_parse_demo' panicked at 'assertion failed: `(left == right)`
  left: `1`,
 right: `0`: the test returned a termination value with a non-zero status code (1) which indicates a failure', C:\Users\user\.rustup\toolchains\nightly-x86_64-pc-windows-msvc\lib/rustlib/src/rust\library\test\src\lib.rs:192:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    tests::test_parse_demo

test result: FAILED. 1 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s
```

**Comment by vkill** [comment]
> But the test on master branch is broken as well.

The master branch is no problem.

**Comment by snylonue** [comment]
The test has passed now.

**Comment by snylonue** [comment]
> 
> 
> > But the test on master branch is broken as well.
> 
> The master branch is no problem.

It seems to be caused by windows (an unexpected `\r` character). Anyway, it is ok.

**Comment by vkill** [comment]
> It seems to be caused by windows (an unexpected `\r` character)

Oh, Can you provide a test file in windows?

**Pull request closed without merging**
